// Bello 3D Model Integration for VetScan Pro
// Generated by Blender Export Pipeline

class BelloModel {
    constructor() {
        this.models = new Map();
        this.currentMode = 'normal';
        this.loadingPromises = new Map();
    }
    
    async loadModel(quality = 'medium') {
        const modelPath = `./assets/models/animals/bello/bello_${quality}.glb`;
        
        if (this.models.has(quality)) {
            return this.models.get(quality);
        }
        
        if (this.loadingPromises.has(quality)) {
            return this.loadingPromises.get(quality);
        }
        
        const loadPromise = this.loadGLTF(modelPath);
        this.loadingPromises.set(quality, loadPromise);
        
        try {
            const model = await loadPromise;
            this.models.set(quality, model);
            this.setupMedicalVisualization(model);
            return model;
        } catch (error) {
            console.error(`Failed to load Bello ${quality}:`, error);
            this.loadingPromises.delete(quality);
            throw error;
        }
    }
    
    setupMedicalVisualization(model) {
        // Setup medical visualization modes
        model.userData = {
            medicalModes: {
                normal: { visible: true, materials: 'fur' },
                xray: { visible: true, materials: 'xray', showSkeleton: true },
                ultrasound: { visible: true, materials: 'ultrasound', showOrgans: true },
                thermal: { visible: true, materials: 'thermal' },
                mri: { visible: true, materials: 'mri' }
            }
        };
    }
    
    switchMedicalMode(mode) {
        this.currentMode = mode;
        // Implementation for switching visualization modes
        console.log(`Switched to ${mode} mode`);
    }
    
    getAnatomyPoints() {
        return {
            heart: new THREE.Vector3(1.2, 0, 1.1),
            lungs: new THREE.Vector3(0.8, 0, 1.2), 
            liver: new THREE.Vector3(0, 0.3, 0.8),
            kidneys: new THREE.Vector3(-1.0, 0, 1.0)
        };
    }
}

// Export for use in VetScan Pro game
export default BelloModel;
